name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: windows-2022
    env:
      IMAGE_NAME: parthibanlearnship/speech-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ github.run_number }} --platform windows/amd64 .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ github.run_number }}